services:
  duplicati:
    image: duplicati/duplicati:latest
    restart: unless-stopped
    command: duplicati-server --webservice-allowed-hostnames=*
    hostname: duplicati-backup
    volumes:
      - /docker/backups/duplicati-data:/data
      - /docker/backups/duplicati-repo:/backups
      - /docker:/docker
    ports:
      - 8200
    networks:
      - backup

networks:
  backup:
    name: backup-network
    external: true